#!/usr/local/bin/node


var utils = require('./buildUtils');
var util = require('util');
var exec = require('child_process').exec;

var filePathsMap = [
	['app/scripts/animations/menu-open.js', 'app/src/utils/animations/menu-open.js'],
	['app/scripts/app.js', 'app/src/init/app.js'],
	['app/scripts/config/req-res.js', 'app/src/config/req-res.js'],
	['app/scripts/config/session.js', 'app/src/config/session.js'],
	['app/scripts/config/urlRouter.js', 'app/src/config/urlRouter.js'],
	['app/scripts/controllers/accountant.js', 'app/src/modules/accountant/accountantCtrl.js'],
	['app/scripts/controllers/billables.js', 'app/src/modules/invoices/billablesCtrl.js'],
	['app/scripts/controllers/bsPopover.js', 'app/src/appframe/navigation/popoverCtrl.js'],
	['app/scripts/controllers/change-password.js', 'app/src/system/suthentication/changePasswordCtrl.js'],
	['app/scripts/controllers/clients.js', 'app/src/modules/entities/clients/clientsCtrl.js'],
	['app/scripts/controllers/clients_create.js', 'app/src/modules/entities/clients/clientsCreateCtrl.js'],
	['app/scripts/controllers/clients_edit.js', 'app/src/modules/entities/clients/clientsEditCtrl.js'],
	['app/scripts/controllers/contracts.js', 'app/src/modules/contracts/contractsCtrl.js'],
	['app/scripts/controllers/contracts_create.js', 'app/src/modules/contracts/contractsCreateCtrl.js'],
	['app/scripts/controllers/contracts_create_build.js', 'app/src/modules/contracts/contractsCreateBuildCtrl.js'],
	['app/scripts/controllers/contracts_create_setup.js', 'app/src/modules/contracts/contractsCreateSetupCtrl.js'],
	['app/scripts/controllers/contracts_manage.js', 'app/src/modules/contracts/contractsManageCtrl.js'],
	['app/scripts/controllers/dashboard.js', 'app/src/modules/dashboard/dashboardCtrl.js'],
	['app/scripts/controllers/departments.js', 'app/src/modules/departments/departmentsCtrl.js'],
	['app/scripts/controllers/indexing.js', 'app/src/system/indexing/indexingCtrl.js'],
	['app/scripts/controllers/kAdminCompanyInfoCtrl.js', 'app/src/modules/tenants/admin/adminCompanyInfoCtrl.js'],
	['app/scripts/controllers/kAdminCtrl.js', 'app/src/modules/tenants/adminCtrl.js'],
	['app/scripts/controllers/kAdminGeneralInfoCtrl.js', 'app/src/modules/tenants/adminGeneralInfoCtrl.js'],
	['app/scripts/controllers/kAdminIndexCtrl.js', 'app/src/modules/tenants/adminIndexCtrl.js'],
	['app/scripts/controllers/kAdminRatesCtrl.js', 'app/src/modules/tenants/adminRatesCtrl.js'],
	['app/scripts/controllers/kAdminStructureCtrl.js', 'app/src/modules/tenants/adminStructureCtrl.js'],
	['app/scripts/controllers/kAdminUsersCtrl.js', 'app/src/modules/tenants/adminUsersCtrl.js'],
	['app/scripts/controllers/kNotificationsCtrl.js', 'app/src/appframe/notifications/notificationsCtrl.js'],
	['app/scripts/controllers/kPaymentsManageCtrl.js', 'app/src/modules/payments/paymentsManageCtrl.js'],
	['app/scripts/controllers/kPrivilegesCtrl.js', 'app/src/system/privileges/privilegesCtrl.js'],
	['app/scripts/controllers/kSchedulesCtrl.js', 'app/src/modules/resources/resourcesScheduleWeekCtrl.js'],
	['app/scripts/controllers/landingCtrl.js', 'app/src/system/authentication/landingCtrl.js'],
	['app/scripts/controllers/login.js', 'app/src/system/authentication/loginCtrl.js'],
	['app/scripts/controllers/logout.js', 'app/src/system/authentication/logoutCtrl.js'],
	['app/scripts/controllers/main.js', 'app/src/appframe/mainCtrl.js'],
	['app/scripts/controllers/menuPanelCtrl.js', 'app/src/appframe/menu/menuPanelCtrl.js'],
	['app/scripts/controllers/new-tenant.js', 'app/src/debug/newTenantCtrl.js'],
	['app/scripts/controllers/payable-detail.js', 'app/src/modules/bills/payableDetailCtrl.js'],
	['app/scripts/controllers/payable-manage.js', 'app/src/modules/bills/payableManageCtrl.js'],
	['app/scripts/controllers/projects.js', 'app/src/modules/projects/projectsCtrl.js'],
	['app/scripts/controllers/projects_create.js', 'app/src/modules/projects/projectsCreateCtrl.js'],
	['app/scripts/controllers/projects_edit.js', 'app/src/modules.projects/projectsEditCtrl.js'],
	['app/scripts/controllers/purchase-request-create.js', 'app/src/modules/requests/requestCreateCtrl.js'],
	['app/scripts/controllers/purchase-request-manage.js', 'app/src/modules/requests/requestManageCtrl.js'],
	['app/scripts/controllers/purchase-request-review-detail.js', 'app/src/modules/requests/requestReviewDetailCtrl.js'],
	['app/scripts/controllers/receivables-create.js', 'app/src/modules/invoices/receivablesCreateCtrl.js'],
	['app/scripts/controllers/receivables-manage.js', 'app/src/modules/invoices/receivablesManageCtrl.js'],
	['app/scripts/controllers/resourceScheduleDayCtrl.js', 'app/src/modules/resources/resourceScheduleDayCtrl.js'],
	['app/scripts/controllers/setup-begin.js', 'app/src/modules/tenants/setup/setupBeginCtrl.js'],
	['app/scripts/controllers/setup-company.js', 'app/src/modules/tenants/setup/setupCompanyCtrl.js'],
	['app/scripts/controllers/setup-complete.js', 'app/src/modules/tenants/setup/setupCompleteCtrl.js'],
	['app/scripts/controllers/setup-general.js', 'app/src/modules/tenants/setup/setupGeneralCtrl.js'],
	['app/scripts/controllers/setup-index.js', 'app/src/modules/tenants/setup/setupIndexCtrl.js'],
	['app/scripts/controllers/setup-quickbooks.js', 'app/src/modules/tenants/setup/setupQuickbooksCtrl.js'],
	['app/scripts/controllers/setup-structure-time.js', 'app/src/modules/tenants/setup/setupStructureTimeCtrl.js'],
	['app/scripts/controllers/setup-structure.js', 'app/src/modules/tenants/setup/setupStructureCtrl.js'],
	['app/scripts/controllers/setup-users.js', 'app/src/modules/tenants/setup/setupUsersCtrl.js'],
	['app/scripts/controllers/setup.js', 'app/src/modules/entities/setup/setupCtrl.js'],
	['app/scripts/controllers/sockets.js', 'app/src/debug/socketsCtrl.js'],
	['app/scripts/controllers/timetracker.js', 'app/src/modules/timesheets/timesheetsCtrl.js'],
	['app/scripts/controllers/timetracker_entry.js', 'app/src/modules/timesheets/timesheetsEntryCtrl.js'],
	['app/scripts/controllers/timetracker_review.js', 'app/src/modules/timesheets/timesheetsReviewCtrl.js'],
	['app/scripts/controllers/utilities_user-select.js', '../saved_ctrls/utilities_user-select.js'],
	['app/scripts/controllers/vendors.js', 'app/src/modules/entities/vendors/vendorsCtrl.js'],
	['app/scripts/controllers/vendors_create.js', 'app/src/modules/entities/vendors/vendorsCreateCtrl.js'],
	['app/scripts/controllers/vendors_edit.js', 'app/src/modules/entities/vendors/vendorsEditCtrl.js'],
	['app/scripts/directives/activeItem.js', 'app/src/utils/directives/kActiveItem.js'],
	['app/scripts/directives/authenticate.js', 'app/src/utils/directives/kAuthenticate.js'],
	['app/scripts/directives/bodyClasses.js', 'app/src/utils/directives/kBodyClasses.js'],
	['app/scripts/directives/datePicker.js', 'app/src/utils/directives/kDatePicker.js'],
	['app/scripts/directives/disallowed.js', 'app/src/utils/directives/kDisallowed.js'],
	['app/scripts/directives/dndModule.js', 'app/src/utils/directives/kDndModule.js'],
	['app/scripts/directives/dragGroup.js', 'app/src/utils/directives/kDragGroup.js'],
	['app/scripts/directives/dragItem.js', 'app/src/utils/directives/kDragItem.js'],
	['app/scripts/directives/dropSpot.js', 'app/src/utils/directives/kDropSpot.js'],
	['app/scripts/directives/dropSpotGroup.js', 'app/src/utils/directives/kDropSpotGroup.js'],
	['app/scripts/directives/editInPlace.js', 'app/src/utils/directives/kEditInPlace.js'],
	['app/scripts/directives/entityManagerList.js', 'app/src/utils/directives/kEntityManagerList.js'],
	['app/scripts/directives/fileDropModule.js', 'app/src/utils/directives/kFileDropModule.js'],
	['app/scripts/directives/fileListModule.js', 'app/src/utils/directives/kFileListModule.js'],
	['app/scripts/directives/flashWarning.js', 'app/src/utils/directives/kFlashWarning.js'],
	['app/scripts/directives/hide-for.js', 'app/src/utils/directives/kHide-for.js'],
	['app/scripts/directives/hoverShow.js', 'app/src/utils/directives/kHoverShow.js'],
	['app/scripts/directives/inputError.js', 'app/src/utils/directives/kInputError.js'],
	['app/scripts/directives/isActive.js', 'app/src/utils/directives/kIsActive.js'],
	['app/scripts/directives/kAnnouncement.js', 'app/src/utils/directives/kAnnouncement.js'],
	['app/scripts/directives/kErrorsTarget.js', 'app/src/utils/directives/kErrorsTarget.js'],
	['app/scripts/directives/kIsFlagged.js', 'app/src/utils/directives/kIsFlagged.js'],
	['app/scripts/directives/kLabel.js', 'app/src/utils/directives/kLabel.js'],
	['app/scripts/directives/kMask.js', 'app/src/utils/directives/kMask.js'],
	['app/scripts/directives/kMatch.js', 'app/src/utils/directives/kMatch.js'],
	['app/scripts/directives/kMaxvalue.js', 'app/src/utils/directives/kMaxvalue.js'],
	['app/scripts/directives/kMenuPanelItem.js', 'app/src/utils/directives/kMenuPanelItem.js'],
	['app/scripts/directives/kMenuPanelToggle.js', 'app/src/utils/directives/kMenuPanelToggle.js'],
	['app/scripts/directives/kMinvalue.js', 'app/src/utils/directives/kMinvalue.js'],
	['app/scripts/directives/kPaymentsTooltip.js', 'app/src/utils/directives/kPaymentsTooltip.js'],
	['app/scripts/directives/kRequiredUnless.js', 'app/src/utils/directives/kRequiredUnless.js'],
	['app/scripts/directives/kRightClickLineItem.js', 'app/src/utils/directives/kRightClickLineItem.js'],
	['app/scripts/directives/kStatusDisplay.js', 'app/src/utils/directives/kStatusDisplay.js'],
	['app/scripts/directives/kValidate.js', 'app/src/utils/directives/kValidate.js'],
	['app/scripts/directives/kValidateTypeahead.js', 'app/src/utils/directives/kValidateTypeahead.js'],
	['app/scripts/directives/kWeeklyDatepicker.js', 'app/src/utils/directives/kWeeklyDatepicker.js'],
	['app/scripts/directives/limitValue.js', 'app/src/utils/directives/kLimitValue.js'],
	['app/scripts/directives/logged-in.js', 'app/src/utils/directives/kLoggedIn.js'],
	['app/scripts/directives/modal.js', 'app/src/utils/directives/Modal.js'],
	['app/scripts/directives/nested-multi-sortable.js', 'app/src/utils/directives/kNestedMultiSortable.js'],
	['app/scripts/directives/orderBy.js', 'app/src/utils/directives/kOrderBy.js'],
	['app/scripts/directives/peerRequired.js', 'app/src/utils/directives/kPeerRequired.js'],
	['app/scripts/directives/pkModal.js', 'app/src/utils/directives/kModal.js'],
	['app/scripts/directives/pkTypeahead.js', 'app/src/utils/directives/kTypeahead.js'],
	['app/scripts/directives/positive-number.js', 'app/src/utils/directives/kPositiveNumber.js'],
	['app/scripts/directives/showItems.js', 'app/src/utils/directives/kShowItems.js'],
	['app/scripts/directives/spin-handler.js', 'app/src/utils/directives/kSpinHandler.js'],
	['app/scripts/directives/spinner.js', 'app/src/utils/directives/kSpinner.js'],
	['app/scripts/directives/state-class.js', 'app/src/utils/directives/kStateClass.js'],
	['app/scripts/directives/timesheet.js', 'app/src/utils/directives/kTimesheet.js'],
	['app/scripts/directives/toggle-sidebar.js', 'app/src/utils/directives/kToggleSidebar.js'],
	['app/scripts/directives/toggle.js', 'app/src/utils/directives/kToggle.js'],
	['app/scripts/directives/toggleTimeInputForm.js', 'app/src/utils/directives/kToggleTimeInputForm.js'],
	['app/scripts/directives/uid.js', 'app/src/utils/directives/kUid.js'],
	['app/scripts/directives/unique-email.js', 'app/src/utils/directives/kUniqueEmail.js'],
	['app/scripts/directives/zipcode.js', 'app/src/utils/directives/kZipcode.js'],
	['app/scripts/filters/capitalize.js', 'app/src/utils/filters/capitalize.js'],
	['app/scripts/filters/getAllByKey.js', 'app/src/utils/filters/getAllByKey.js'],
	['app/scripts/filters/getAllWithoutKey.js', 'app/src/utils/filters/getAllWithoutKey.js'],
	['app/scripts/filters/getAndModifyObjectByKey.js', 'app/src/utils/filters/getAndModifyObjectByKey.js'],
	['app/scripts/filters/getByKey.js', 'app/src/utils/filters/getByKey.js'],
	['app/scripts/filters/getIndexByKey.js', 'app/src/utils/filters/getIndexByKey.js'],
	['app/scripts/filters/itemById.js', 'app/src/utils/filters/itemById.js'],
	['app/scripts/filters/orderByKey.js', 'app/src/utils/filters/orderByKey.js'],
	['app/scripts/filters/permissions.js', 'app/src/utils/filters/permissions.js'],
	['app/scripts/filters/splitFilter.js', 'app/src/utils/filters/splitFilter.js'],
	['app/scripts/filters/titleize.js', 'app/src/utils/filters/titleize.js'],
	['app/scripts/services/AccountSvc.js', 'app/src/data/http/Account.js'],
	['app/scripts/services/Api.js', 'app/src/data/http/Api.js'],
	['app/scripts/services/CalendarGrid.js', 'app/src/modules/timesheets/CalendarGrid.js'],
	['app/scripts/services/Clients.js', 'app/src/data/http/Clients.js'],
	['app/scripts/services/Company.js', 'app/src/data/http/Company.js'],
	['app/scripts/services/Contract.js', 'app/src/modules/contracts/Contract.js'],
	['app/scripts/services/Contracts.js', 'app/src/data/http/Contracts.js'],
	['app/scripts/services/Data.js', 'app/src/data/Data.js'],
	['app/scripts/services/Datastore.js', 'app/src/data/Datastore.js'],
	['app/scripts/services/Deliverable.js', 'app/src/modules/contracts/Deliverable.js'],
	['app/scripts/services/Departments.js', 'app/src/data/http/Departments.js'],
	['app/scripts/services/DocumentsSvc.js', 'app/src/data/http/Documents.js'],
	['app/scripts/services/EntMan.js', 'app/src/system/EntMan.js'],
	['app/scripts/services/ErrorHandler.js', 'app/src/system/ErrorHandler.js'],
	['app/scripts/services/FormReset.js', 'app/src/utils/FormReset.js'],
	['app/scripts/services/IndexingSvc.js', 'app/src/data/http/Indexing.js'],
	['app/scripts/services/Invoices.js', 'app/src/data/http/Invoices.js'],
	['app/scripts/services/LabelMaker.js', 'app/src/system/LabelMaker.js'],
	['app/scripts/services/LocalStorageCache.js', 'app/src/system/LocalStorageCache.js'],
	['app/scripts/services/Modals.js', 'app/src/utils/Modals.js'],
	['app/scripts/services/PayablesSvc.js', 'app/src/data/http/Payables.js'],
	['app/scripts/services/Persist.js', 'app/src/data/Persist.js'],
	['app/scripts/services/Projects.js', 'app/src/data/http/Projects.js'],
	['app/scripts/services/PurchaseRequests.js', 'app/src/modules/requests/PurchaseRequests.js'],
	['app/scripts/services/Requests.js', 'app/src/modules/requests/Requests.js'],
	['app/scripts/services/ResourceScheduleDaySvc.js', 'app/src/modules/resources/resourceScheduleDaySvc.js'],
	['app/scripts/services/SaaSSvc.js', 'app/src/system/SaaSSvc.js'],
	['app/scripts/services/Spin.js', 'app/src/appframe/spinnerSvc.js'],
	['app/scripts/services/Timesheet.js', 'app/src/modules/timesheets/Timesheet.js'],
	['app/scripts/services/Timesheets.js', 'app/src/data/http/Timesheets.js'],
	['app/scripts/services/Toastr.js', 'app/src/system/Toastr.js'],
	['app/scripts/services/Typeahead.js', 'app/src/utils/Typeahead.js'],
	['app/scripts/services/TypeaheadSpecific.js', 'app/src/utils/TypeaheadSpecific.js'],
	['app/scripts/services/User.js', 'app/src/data/http/User.js'],
	['app/scripts/services/Utilities.js', 'app/src/utils/Utilities.js'],
	['app/scripts/services/Validation.js', 'app/src/init/validation.js'],
	['app/scripts/services/ValidationHelper.js', 'app/src/system/validation/ValidationHelper.js'],
	['app/scripts/services/Vendors.js', 'app/src/modules/data/http/Vendors.js'],
	['app/scripts/services/accountant.js', 'app/src/modules/accountant/accountantSvc.js'],
	['app/scripts/services/cookieSvc.js', 'app/src/system/authentication/cookieSvc.js'],
	['app/scripts/services/dashboardSvc.js', 'app/src/modules/dashboard/dashboardSvc.js'],
	['app/scripts/services/kDataCacheSvc.js', 'app/src/data/socket/DataCache.js'],
	['app/scripts/services/kNotificationsSvc.js', 'app/src/appframe/notifications/notificationSvc.js'],
	['app/scripts/services/kPaymentsSvc.js', 'app/src/modules/payments/paymentsSvc.js'],
	['app/scripts/services/kPrivilegesSvc.js', 'app/src/system/privileges/privilegesSvc.js'],
	['app/scripts/services/kSignalRSvc.js', 'app/src/data/socket/SignalR.js'],
	['app/scripts/services/lodashSvc.js', 'app/src/globals/lodash.js'],
	['app/scripts/services/menuPanelSvc.js', 'app/src/appframe/menu/menuPanelSvc.js'],
	['app/scripts/services/plurals.js', 'app/src/utils/pluralsSvc.js'],
	['app/scripts/services/setup-storage.js', 'app/src/modules/tenants/setup/setupStorageSvc.js'],
	['app/scripts/states/accountant.js', 'app/src/modules/accountant/states.js'],
	['app/scripts/states/admin.js', 'app/src/modules/tenants/admin/states.js'],
	['app/scripts/states/authentication.js', 'app/src/system/authentication/states.js'],
	['app/scripts/states/bills.js', 'app/src/modules/bills/states.js'],
	['app/scripts/states/clients.js', 'app/src/modules/clients/states.js'],
	['app/scripts/states/contracts.js', 'app/src/modules/contracts/states.js'],
	['app/scripts/states/dashboard.js', 'app/src/modules/dashboard/states.js'],
	['app/scripts/states/debug.js', 'app/src/debug/states.js'],
	['app/scripts/states/departments.js', 'app/src/modules/departments/states.js'],
	['app/scripts/states/indexing.js', 'app/src/system/indexing/states.js'],
	['app/scripts/states/invoices.js', 'app/src/modules/invoices/states.js'],
	['app/scripts/states/landing.js', 'app/src/system/landing/states.js'],
	['app/scripts/states/payments.js', 'app/src/modules/payments/states.js'],
	['app/scripts/states/projects.js', 'app/src/modules/projects/states.js'],
	['app/scripts/states/requests.js', 'app/src/modules/requests/states.js'],
	['app/scripts/states/resources.js', 'app/src/modules/resources/states.js'],
	['app/scripts/states/setup.js', 'app/src/modules/tenants/setup/states.js'],
	['app/scripts/states/timesheets.js', 'app/src/modules/timesheets/states.js'],
	['app/scripts/states/vendors.js', 'app/src/modules/entities/vendors/states.js'],
	['app/scripts/validations/authentication.js', 'app/src/system/authentication/validations.js'],
	['app/scripts/validations/bills.js', 'app/src/modules/bills/validations.js'],
	['app/scripts/validations/config.js', 'app/src/config/validations.js'],
	['app/scripts/validations/contracts.js', 'app/src/modules/contracts/validations.js'],
	['app/scripts/validations/entities.js', 'app/src/modules/entities/validations.js'],
	['app/scripts/validations/indexing.js', 'app/src/system/indexing/validations.js'],
	['app/scripts/validations/invoices.js', 'app/src/modules/invoices/validations.js'],
	['app/scripts/validations/projects.js', 'app/src/modules/projects/validations.js'],
	['app/scripts/validations/requests.js', 'app/src/modules/requests/validations.js'],
	['app/scripts/validations/tenant.js', 'app/src/modules/tenants/validations.js'],
	['app/scripts/validations/timesheets.js', 'app/src/modules/timesheets/validations.js']
];


var fileNamesBefore = [ 
	'app/views/accountant.html',
	'app/views/admin-company-info.html',
	'app/views/admin-general-info.html',
	'app/views/admin-index.html',
	'app/views/admin-rates.html',
	'app/views/admin-structure.html',
	'app/views/admin-users.html',
	'app/views/admin.html',
	'app/views/billables.html',
	'app/views/changePassword.html',
	'app/views/clients.html',
	'app/views/clients_create.html',
	'app/views/contracts.html',
	'app/views/contracts_create.html',
	'app/views/contracts_create_build.html',
	'app/views/contracts_create_setup.html',
	'app/views/contracts_manage.html',
	'app/views/dashboard.html',
	'app/views/department-create-modal.html',
	'app/views/department-delete-modal.html',
	'app/views/department-update-modal.html',
	'app/views/departments-detail.html',
	'app/views/departments-index.html',
	'app/views/departments-manage.html',
	'app/views/guide-me.html',
	'app/views/indexing.html',
	'app/views/landing.html',
	'app/views/login.html',
	'app/views/main.html',
	'app/views/menu-panel.html',
	'app/views/more-nav-items.html',
	'app/views/newTenant.html',
	'app/views/payable-detail.html',
	'app/views/payable-manage.html',
	'app/views/payments-manage.html',
	'app/views/projects.html',
	'app/views/projects_create.html',
	'app/views/projects_edit.html',
	'app/views/purchase-request-all-items-modal.html',
	'app/views/purchase-request-client-add-new-modal.html',
	'app/views/purchase-request-comments-modal.html',
	'app/views/purchase-request-create-popover.html',
	'app/views/purchase-request-create.html',
	'app/views/purchase-request-decline-purchase-modal.html',
	'app/views/purchase-request-document-preview-modal.html',
	'app/views/purchase-request-manage.html',
	'app/views/purchase-request-pass-expenses-modal.html',
	'app/views/purchase-request-projects-all-modal.html',
	'app/views/purchase-request-request-info-modal.html',
	'app/views/purchase-request-review-alert-modal.html',
	'app/views/purchase-request-review-alert-time-modal.html',
	'app/views/purchase-request-review-detail.html',
	'app/views/purchase-request-review-forward-confirmation-modal.html',
	'app/views/purchase-request-review-forward-modal.html',
	'app/views/purchase-request-review-more-info-modal.html',
	'app/views/purchase-request-review.html',
	'app/views/purchase-request-vendor-add-new-modal.html',
	'app/views/purchase-request-vendor-select-modal.html',
	'app/views/receivables-create.html',
	'app/views/receivables-manage.html',
	'app/views/resource-schedule.html',
	'app/views/schedules.html',
	'app/views/setup-begin.html',
	'app/views/setup-company-configurebyday-popover.html',
	'app/views/setup-company.html',
	'app/views/setup-complete.html',
	'app/views/setup-designated.html',
	'app/views/setup-general.html',
	'app/views/setup-index.html',
	'app/views/setup-nav.html',
	'app/views/setup-quickbooks.html',
	'app/views/setup-structure-time.html',
	'app/views/setup-structure.html',
	'app/views/setup-users.html',
	'app/views/setup.html',
	'app/views/sidebar-first.html',
	'app/views/sidebar-second.html',
	'app/views/sockets.html',
	'app/views/system_company-info.html',
	'app/views/system_departments.html',
	'app/views/system_general-info.html',
	'app/views/system_index.html',
	'app/views/system_users.html',
	'app/views/timetracker.html',
	'app/views/timetracker_entry.html',
	'app/views/timetracker_review.html',
	'app/views/utilities_index.html',
	'app/views/utilities_labels.html',
	'app/views/utilities_local-storage-cache.html',
	'app/views/utilities_user-select.html',
	'app/views/vendors.html',
	'app/views/vendors_create.html',
	'app/views/vendors_edit.html'
];

var fileNamesAfter = [
	'app/views/modules/accountant/accountant.html',
	'app/views/modules/admin/company-info.html',
	'app/views/modules/admin/general-info.html',
	'app/views/modules/admin/index.html',
	'app/views/modules/admin/rates.html',
	'app/views/modules/admin/structure.html',
	'app/views/modules/admin/users.html',
	'app/views/modules/admin/admin.html',
	'app/views/modules/invoices/billables-manage.html',
	'app/views/system/authentication/change-password.html',
	'app/views/modules/clients/index.html',
	'app/views/modules/clients/create.html',
	'app/views/modules/contracts/index.html',
	'app/views/modules/contracts/create.html',
	'app/views/modules/contracts/create-build.html',
	'app/views/modules/contracts/create-setup.html',
	'app/views/modules/contracts/manage.html',
	'app/views/modules/dashboard/index.html',
	'app/views/templates/modals/department-create-modal.html',
	'app/views/templates/modals/department-delete-modal.html',
	'app/views/templates/modals/department-update-modal.html',
	'app/views/modules/departments/detail.html',
	'app/views/modules/departments/index.html',
	'app/views/modules/departments/manage.html',
	'app/views/appframe/footer/guide-me.html',
	'app/views/system/indexing/indexing.html',
	'app/views/system/authentication/landing.html',
	'app/views/system/authentication/login.html',
	'app/views/appframe/content/main.html',
	'app/views/appframe/menu/menu-panel.html',
	'app/views/appframe/navigation/more-nav-items.html',
	'app/views/debug/newTenant.html',
	'app/views/modules/bills/detail.html',
	'app/views/modules/bills/manage.html',
	'app/views/modules/payments/manage.html',
	'app/views/modules/projects/index.html',
	'app/views/modules/projects/create.html',
	'app/views/modules/projects/edit.html',
	'app/views/templates/modals/request-all-items-modal.html',
	'app/views/templates/modals/request-client-add-new-modal.html',
	'app/views/templates/modals/request-comments-modal.html',
	'app/views/modules/requests/create-popover.html',
	'app/views/modules/requests/create.html',
	'app/views/templates/modals/request-decline-purchase-modal.html',
	'app/views/templates/modals/request-document-preview-modal.html',
	'app/views/modules/requests/manage.html',
	'app/views/templates/modals/request-pass-expenses-modal.html',
	'app/views/templates/modals/request-projects-all-modal.html',
	'app/views/templates/modals/request-request-info-modal.html',
	'app/views/templates/modals/request-review-alert-modal.html',
	'app/views/templates/modals/request-review-alert-time-modal.html',
	'app/views/modules/requests/review-detail.html',
	'app/views/templates/modals/request-review-forward-confirmation-modal.html',
	'app/views/templates/modals/request-review-forward-modal.html',
	'app/views/templates/modals/request-review-more-info-modal.html',
	'app/views/modules/requests/review.html',
	'app/views/templates/modals/request-vendor-add-new-modal.html',
	'app/views/templates/modals/request-vendor-select-modal.html',
	'app/views/modules/invoices/create.html',
	'app/views/modules/invoices/manage.html',
	'app/views/modules/resources/schedule-day.html',
	'app/views/modules/resources/schedules-week.html',
	'app/views/modules/setup/begin.html',
	'app/views/modules/setup/company-configurebyday-popover.html',
	'app/views/modules/setup/company.html',
	'app/views/modules/setup/complete.html',
	'app/views/modules/setup/designated.html',
	'app/views/modules/setup/general.html',
	'app/views/modules/setup/index.html',
	'app/views/modules/setup/nav.html',
	'app/views/modules/setup/quickbooks.html',
	'app/views/modules/setup/structure-time.html',
	'app/views/modules/setup/structure.html',
	'app/views/modules/setup/users.html',
	'app/views/modules/setup/setup.html',
	'app/views/appframe/navigation/index.html',
	'app/views/appframe/notifications/index.html',
	'app/views/debug/sockets.html',
	'app/views/system_company-info.html',
	'app/views/system_departments.html',
	'app/views/system_general-info.html',
	'app/views/system_index.html',
	'app/views/system_users.html',
	'app/views/modules/timesheets/index.html',
	'app/views/modules/timesheets/entry.html',
	'app/views/modules/timesheets/review.html',
	'app/views/utilities_index.html',
	'app/views/utilities_labels.html',
	'app/views/utilities_local-storage-cache.html',
	'app/views/utilities_user-select.html',
	'app/views/modules/vendors/index.html',
	'app/views/modules/vendors/create.html',
	'app/views/modules/vendors/edit.html'
];

// current paths
var viewPathsBefore = [ 
	'views/accountant.html',
	'views/admin-company-info.html',
	'views/admin-general-info.html',
	'views/admin-index.html',
	'views/admin-rates.html',
	'views/admin-structure.html',
	'views/admin-users.html',
	'views/admin.html',
	'views/billables.html',
	'views/changePassword.html',
	'views/clients.html',
	'views/clients_create.html',
	'views/contracts.html',
	'views/contracts_create.html',
	'views/contracts_create_build.html',
	'views/contracts_create_setup.html',
	'views/contracts_manage.html',
	'views/dashboard.html',
	'views/department-create-modal.html',
	'views/department-delete-modal.html',
	'views/department-update-modal.html',
	'views/departments-detail.html',
	'views/departments-index.html',
	'views/departments-manage.html',
	'views/guide-me.html',
	'views/indexing.html',
	'views/landing.html',
	'views/login.html',
	'views/main.html',
	'views/menu-panel.html',
	'views/more-nav-items.html',
	'views/newTenant.html',
	'views/payable-detail.html',
	'views/payable-manage.html',
	'views/payments-manage.html',
	'views/projects.html',
	'views/projects_create.html',
	'views/projects_edit.html',
	'views/purchase-request-all-items-modal.html',
	'views/purchase-request-client-add-new-modal.html',
	'views/purchase-request-comments-modal.html',
	'views/purchase-request-create-popover.html',
	'views/purchase-request-create.html',
	'views/purchase-request-decline-purchase-modal.html',
	'views/purchase-request-document-preview-modal.html',
	'views/purchase-request-manage.html',
	'views/purchase-request-pass-expenses-modal.html',
	'views/purchase-request-projects-all-modal.html',
	'views/purchase-request-request-info-modal.html',
	'views/purchase-request-review-alert-modal.html',
	'views/purchase-request-review-alert-time-modal.html',
	'views/purchase-request-review-detail.html',
	'views/purchase-request-review-forward-confirmation-modal.html',
	'views/purchase-request-review-forward-modal.html',
	'views/purchase-request-review-more-info-modal.html',
	'views/purchase-request-review.html',
	'views/purchase-request-vendor-add-new-modal.html',
	'views/purchase-request-vendor-select-modal.html',
	'views/receivables-create.html',
	'views/receivables-manage.html',
	'views/resource-schedule.html',
	'views/schedules.html',
	'views/setup-begin.html',
	'views/setup-company-configurebyday-popover.html',
	'views/setup-company.html',
	'views/setup-complete.html',
	'views/setup-designated.html',
	'views/setup-general.html',
	'views/setup-index.html',
	'views/setup-nav.html',
	'views/setup-quickbooks.html',
	'views/setup-structure-time.html',
	'views/setup-structure.html',
	'views/setup-users.html',
	'views/setup.html',
	'views/sidebar-first.html',
	'views/sidebar-second.html',
	'views/sockets.html',
	'views/system_company-info.html',
	'views/system_departments.html',
	'views/system_general-info.html',
	'views/system_index.html',
	'views/system_users.html',
	'views/timetracker.html',
	'views/timetracker_entry.html',
	'views/timetracker_review.html',
	'views/utilities_index.html',
	'views/utilities_labels.html',
	'views/utilities_local-storage-cache.html',
	'views/utilities_user-select.html',
	'views/vendors.html',
	'views/vendors_create.html',
	'views/vendors_edit.html'
];

// link change for views
var viewPathsAfter = [
	'views/modules/accountant/accountant.html',
	'views/modules/admin/company-info.html',
	'views/modules/admin/general-info.html',
	'views/modules/admin/index.html',
	'views/modules/admin/rates.html',
	'views/modules/admin/structure.html',
	'views/modules/admin/users.html',
	'views/modules/admin/admin.html',
	'views/modules/invoices/billables-manage.html',
	'views/system/authentication/change-password.html',
	'views/modules/clients/index.html',
	'views/modules/clients/create.html',
	'views/modules/contracts/index.html',
	'views/modules/contracts/create.html',
	'views/modules/contracts/create-build.html',
	'views/modules/contracts/create-setup.html',
	'views/modules/contracts/manage.html',
	'views/modules/dashboard/index.html',
	'views/templates/modals/department-create-modal.html',
	'views/templates/modals/department-delete-modal.html',
	'views/templates/modals/department-update-modal.html',
	'views/modules/departments/detail.html',
	'views/modules/departments/index.html',
	'views/modules/departments/manage.html',
	'views/appframe/footer/guide-me.html',
	'views/system/indexing/indexing.html',
	'views/system/authentication/landing.html',
	'views/system/authentication/login.html',
	'views/appframe/content/main.html',
	'views/appframe/menu/menu-panel.html',
	'views/appframe/navigation/more-nav-items.html',
	'views/debug/newTenant.html',
	'views/modules/bills/detail.html',
	'views/modules/bills/manage.html',
	'views/modules/payments/manage.html',
	'views/modules/projects/index.html',
	'views/modules/projects/create.html',
	'views/modules/projects/edit.html',
	'views/templates/modals/request-all-items-modal.html',
	'views/templates/modals/request-client-add-new-modal.html',
	'views/templates/modals/request-comments-modal.html',
	'views/modules/requests/create-popover.html',
	'views/modules/requests/create.html',
	'views/templates/modals/request-decline-purchase-modal.html',
	'views/templates/modals/request-document-preview-modal.html',
	'views/modules/requests/manage.html',
	'views/templates/modals/request-pass-expenses-modal.html',
	'views/templates/modals/request-projects-all-modal.html',
	'views/templates/modals/request-request-info-modal.html',
	'views/templates/modals/request-review-alert-modal.html',
	'views/templates/modals/request-review-alert-time-modal.html',
	'views/modules/requests/review-detail.html',
	'views/templates/modals/request-review-forward-confirmation-modal.html',
	'views/templates/modals/request-review-forward-modal.html',
	'views/templates/modals/request-review-more-info-modal.html',
	'views/modules/requests/review.html',
	'views/templates/modals/request-vendor-add-new-modal.html',
	'views/templates/modals/request-vendor-select-modal.html',
	'views/modules/invoices/create.html',
	'views/modules/invoices/manage.html',
	'views/modules/resources/schedule-day.html',
	'views/modules/resources/schedules-week.html',
	'views/modules/setup/begin.html',
	'views/modules/setup/company-configurebyday-popover.html',
	'views/modules/setup/company.html',
	'views/modules/setup/complete.html',
	'views/modules/setup/designated.html',
	'views/modules/setup/general.html',
	'views/modules/setup/index.html',
	'views/modules/setup/nav.html',
	'views/modules/setup/quickbooks.html',
	'views/modules/setup/structure-time.html',
	'views/modules/setup/structure.html',
	'views/modules/setup/users.html',
	'views/modules/setup/setup.html',
	'views/appframe/navigation/index.html',
	'views/appframe/notifications/index.html',
	'views/debug/sockets.html',
	'views/system_company-info.html',
	'views/system_departments.html',
	'views/system_general-info.html',
	'views/system_index.html',
	'views/system_users.html',
	'views/modules/timesheets/index.html',
	'views/modules/timesheets/entry.html',
	'views/modules/timesheets/review.html',
	'views/utilities_index.html',
	'views/utilities_labels.html',
	'views/utilities_local-storage-cache.html',
	'views/utilities_user-select.html',
	'views/modules/vendors/index.html',
	'views/modules/vendors/create.html',
	'views/modules/vendors/edit.html'
];

var controllerNamesMap = [
	['AccountantCtrl', 'accountantCtrl'],
	['BillablesCtrl', 'billablesCtrl'],
	['bsPopoverCtrl', 'popoverCtrl'],
	['ChangePasswordCtrl', 'changePasswordCtrl'],
	['ClientsCtrl', 'clientsCtrl'],
	['ClientsCreateCtrl', 'clientsCreateCtrl'],
	['ClientsEditCtrl', 'clientsEditCtrl'],
	['ContractsCtrl', 'contractsCtrl'],
	['ContractsCreateCtrl', 'contractsCreateCtrl'],
	['ContractsCreateBuildCtrl', 'contractsCreateBuildCtrl'],
	['ContractsCreateSetupCtrl', 'contractsCreateSetupCtrl'],
	['ContractsManageCtrl', 'contractsManageCtrl'],
	['DashboardCtrl', 'dashboardCtrl'],
	['DepartmentsCtrl', 'departmentsCtrl'],
	['IndexingCtrl.js', 'indexingCtrl'],
	['kAdminCompanyInfoCtrl', 'adminCompanyInfoCtrl'],
	['kAdminCtrl', 'adminCtrl'],
	['kAdminGeneralInfoCtrl', 'adminGeneralInfoCtrl'],
	['kAdminIndexCtrl', 'adminIndexCtrl'],
	['kAdminRatesCtrl', 'adminRatesCtrl'],
	['kAdminStructureCtrl', 'adminStructureCtrl'],
	['kAdminUsersCtrl', 'adminUsersCtrl'],
	['kNotificationsCtrl', 'notificationsCtrl'],
	['kPaymentsManageCtrl', 'paymentsManageCtrl'],
	['kPrivilegesCtrl', 'privilegesCtrl'],
	['kSchedulesCtrl', 'resourcesScheduleWeekCtrl'],
	['LandingCtrl', 'landingCtrl'],
	['LoginCtrl', 'loginCtrl'],
	['LogoutCtrl', 'logoutCtrl'],
	['MainCtrl', 'mainCtrl'],
	['NewTenantCtrl', 'newTenantCtrl'],
	['PayableDetailCtrl', 'payableDetailCtrl'],
	['PayableManageCtrl', 'payableManageCtrl'],
	['ProjectsCtrl', 'projectsCtrl'],
	['ProjectsCreateCtrl', 'projectsCreateCtrl'],
	['ProjectsEditCtrl', 'projectsEditCtrl'],
	['PurchaseRequestCreateCtrl', 'requestCreateCtrl'],
	['PurchaseRequestManageCtrl', 'requestManageCtrl'],
	['PurchaseRequestReviewDetailCtrl', 'requestReviewDetailCtrl'],
	['ReceivablesCreateCtrl', 'receivablesCreateCtrl'],
	['ReceivablesManageCtrl', 'receivablesManageCtrl'],
	['SetupBeginCtrl', 'setupBeginCtrl'],
	['SetupCompanyCtrl', 'setupCompanyCtrl'],
	['SetupCompleteCtrl', 'setupCompleteCtrl'],
	['SetupGeneralCtrl', 'setupGeneralCtrl'],
	['SetupIndexCtrl', 'setupIndexCtrl'],
	['SetupQuickbooksCtrl', 'setupQuickbooksCtrl'],
	['SetupStructureTimeCtrl', 'setupStructureTimeCtrl'],
	['SetupStructureCtrl', 'setupStructureCtrl'],
	['SetupUsersCtrl', 'setupUsersCtrl'],
	['SetupCtrl', 'asetupCtrl'],
	['SocketsCtrl', 'socketsCtrl'],
	['TimetrackerCtrl', 'timesheetsCtrl'],
	['TimetrackerEntryCtrl', 'timesheetsEntryCtrl'],
	['TimetrackerReviewCtrl', 'timesheetsReviewCtrl'],
	['VendorsCtrl', 'vendorsCtrl'],
	['VendorsCreateCtrl', 'vendorsCreateCtrl'],
	['VendorsEditCtrl', 'vendorsEditCtrl']
];

(function () {
	for (var x = 0; x < fileNamesAfter.length; x++) {
		exec(['git mv', fileNamesBefore[x], fileNamesAfter[x]].join(' '));
	}

	for (var x = 0; x < filePathsMap.length; x++) {
		exec(['git', 'mv', filePathsMap[x][0], filePathsMap[x][1]].join(' '));
	}
}());

utils.recursiveReplace(['app/views', 'app/src'], viewPathsBefore, viewPathsAfter);

utils.recursiveReplace(['app/views', 'app/src'], controllerNamesMap);
